version: '3'
services:
  front:
    build:
      context: ./client
    container_name: front-openweathermap
    restart: unless-stopped
    ports:
      - "4200:4200"
  server:
    build:
      context: .
    container_name: backend-openweathermap
    restart: unless-stopped
    ports:
      - "3000:3000"